Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.provision "shell", path: "deps.sh"
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
  end
end
